# -*- coding: utf-8 -*-
"""Lab ASMT -ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWtJigsyoWLbtHsToEVGb69I9B46Xaba
"""



"""# LAB ASSESMENT Machine Learning

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

**   **

Q15.

Extra Work Implementing LOGESTIC REGRESSION
"""

print(df.describe())
print(df.isnull().sum())



"""# Final Implemented CODE

"""

import numpy as np
import matplotlib.pyplot as plt

data = np.array([
    [2, 3],
    [4, 7],
    [6, 5]
])

X_coords = data[:, 0]
Y_coords = data[:, 1]

plt.figure(figsize=(7, 5))
plt.scatter(X_coords, Y_coords, color='blue', s=100, label='Original Data Points')
plt.title('Scatter Plot of Original Data (X vs Y)')
plt.xlabel('X')
plt.ylabel('Y')
plt.grid(True)
plt.axvline(0, color='gray', linestyle='--', linewidth=0.8)
plt.axhline(0, color='gray', linestyle='--', linewidth=0.8)
plt.legend()
plt.show()

mean = np.mean(data, axis=0)
centered_data = data - mean

print("Centered Data:\n", centered_data)

principal_component_1_eigenvector = np.array([1, 1])

projected_data_pc1 = centered_data @ principal_component_1_eigenvector

print("\nProjected Data (First Principal Component Scores):")
print(projected_data_pc1)

for col in ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']:
    df[col] = df[col].replace(0, df[col].mean())

print(df.describe())

"""Now that the data is cleaned, let's perform Logistic Regression."""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:\n", conf_matrix)