# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_PLvymnD4RHK3uKJeKzhP9y7XF5mJA4

[link text](https://)

# **MACHINE LEARNING ASSIGNMENT :- 1**

#Name :- Ghrushnesh Sudhakar Patil

#Banch:-CSE(AI)        

#Div:- D  Batch:- 3



#PRN:- 12411658        Roll No:- 66

Perform the following operations using Python on suitable data sets:

Read data from different formats (like csv, xls).

Find Shape of Data.

Find Missing Values.

Find data type of each column.

Finding out Zero's.

Indexing and selecting data, sort data,

Describe attributes of data, checking data types of each column,

counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)
"""

import pandas as pd

"""# Read data from different formats (like csv, xls)."""

print(df)

import pandas as pd
import numpy as np

data = {
    "Student_ID": range(1, 16),
    "Name": ["Ghrushnesh", "Harish", "Atharva", "Sagar", "Neha", "Arjun", "Priya",
             "Karan", "Anjali", "Rohit", "Pooja", "Manish", "Rina", "Sunil", "Kavya"],
    "Age": [20, 21, 19, 22, 20, 21, 20, 22, 19, 21, 20, 23, 19, 22, 20],
    "Gender": ["M", "M", "M", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "Course": ["CSE", "IT", "CSE", "ECE", "IT", "CSE", "ECE",
               "ME", "IT", "ME", "CSE", "ECE", "IT", "ME", "CSE"],
    "Marks": [85, 78, 92, 0, 88, 76, np.nan, 69, 91, 65, 89, 72, 95, 60, 84],
    "Attendance": [90, 85, 95, 70, 0, 80, 88, 75, 92, np.nan, 90, 78, 98, 65, 88]
}

df = pd.DataFrame(data)
print(df)

df["Internship"] = ["1", "0", "1", "0", "1",
                    "0", "1", "1", "1", "0",
                    "1", "0", "1", "0", "0"]

print(df)

"""# Find Shape of Data.

"""

print("\nShape of data (Rows, Columns):")
print(df.shape)

"""# Find Missing Values.


"""

# Check missing values column-wise
df.isnull().sum()

# Check if any missing values exist
df.isnull().values.any()

print(df.dtypes)

print(df[["Name", "Age"]])

"""# Finding out Zero's."""

print((df == 0).sum())
df[(df == 0).any(axis=1)]

"""# Find data type of each column."""

df["Marks"]

df[["Name", "Marks", "Attendance"]]

df.iloc[0:5]

df[df["Marks"] > 80]

"""# Indexing and selecting data, sort data,"""

df.sort_values(by="Marks")

df.sort_values(by="Marks", ascending=False)

"""# Describe attributes of data, checking data types of each column,

# Describe Attributes of Data
"""

df.describe()

df.describe(include="object")

"""# Checking Data Types of Each Column

"""

df["Internship"] = ["1", "0", "1", "0", "1",
                    "0", "1", "1", "1", "0",
                    "1", "0", "1", "0", "0"]
df["Internship"] = df["Internship"].astype(int)
df.dtypes

"""# Counting unique values of data, Format of each column, Converting variable data type (e.g. from long to short, vice versa)

# Counting Unique Values
"""

df["Course"].unique()
df

"""# Count of unique values"""

df["Course"].nunique()

"""# Frequency of values"""

df["Course"].value_counts()

"""# Format of Each Column"""

df.applymap(type)
df.apply(lambda x: x.dtype)

"""# ----- Converting Variable Data Type -----

# Convert Age from int → float
"""

df["Age"] = df["Age"].astype(float)
df["Age"].dtype

df["Internship"] = df["Internship"].astype(int)
df["Internship"].dtype
df

df["Course"] = df["Course"].astype("category")
df["Course"].dtype
df

"""# Handle Missing Values"""

df["Marks"].fillna(df["Marks"].mean(), inplace=True)
df

df.dropna(inplace=True)
df