# -*- coding: utf-8 -*-
"""ML-8_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vymh5MTUgV3b-kwfVjXetApIxTiaim4t

# **Machine Learning Assignment :- 8**

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

**   **
Apply appropriate ML algorithm on a dataset collected in a cosmetics shop showing details of customers to predict customer response for special offer. Create confusion matrix based on above data and find

1). Accuracy

2). Precision

3). Recall

4). F-1 score
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

data = pd.DataFrame({
    "CustomerID": [1,2,3,4,5,6,7,8,9,10,
                   11,12,13,14,15,16,17,18,19,20],
    "Age": [22,35,26,45,30,50,28,42,24,38,
            29,41,33,27,36,48,23,39,31,44],
    "Gender": [0,1,0,1,0,1,0,1,0,1,
               0,1,0,0,1,1,0,1,0,1],
    "Income": [25000,40000,32000,60000,45000,70000,38000,52000,28000,48000,
               35000,58000,42000,30000,46000,72000,26000,51000,39000,65000],
    "SpendingScore": [75,40,60,30,55,20,70,35,80,45,
                      65,25,50,85,43,15,78,38,58,33],
    "PreviousPurchases": [5,2,4,1,3,1,6,2,7,3,
                          4,1,5,8,2,1,6,2,4,1],
    "Membership": [1,0,1,0,1,0,1,0,1,0,
                   1,0,1,1,0,0,1,0,1,0],
    "Response": [1,0,1,0,1,0,1,0,1,0,
                 1,0,1,1,0,0,1,0,1,0]
})

print("Dataset:\n")
print(data)

X = data.drop(["CustomerID", "Response"], axis=1)
y = data["Response"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1
)

# Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)


print("\nConfusion Matrix:")
print(cm)

TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP) if (TP + FP) != 0 else 0
recall = TP / (TP + FN) if (TP + FN) != 0 else 0
f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

print("\nEvaluation Metrics:")
print("Accuracy  :", round(accuracy,4))
print("Precision :", round(precision,4))
print("Recall    :", round(recall,4))
print("F1 Score  :", round(f1_score,4))