# -*- coding: utf-8 -*-
"""ML-ASG-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vRLUphNBBgsm7V6_S_8DqWMQzjE6SZG

# **Machine Learning Assignment :- 10**

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

---






Q. 10. Assignment on Regression technique.

Download temperature data from the link below.

DATASET LINK :-https://www.kaggle.com/venky73/temperaturesof-india?select=temperatures.csv

This data consists of temperatures of INDIA averaging the temperatures of all places month wise. Temperatures values are recorded in CELSIUS






1.   Apply Linear Regression using a suitable library function and predict the Month-wise temperature.

2.   Assess the performance of regression models using MSE, MAE and R-Square

3.   Metrics

4.   Visualize a simple regression model.

1. Apply Linear Regression using a suitable library function and predict the Month-wise temperature.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

df = pd.read_csv("temperatures.csv")
df.head()

months = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"]
data = []

for _, row in df.iterrows():
    for i, m in enumerate(months):
        data.append([i+1, row[m]])

long_df = pd.DataFrame(data, columns=["Month", "Temperature"])

X = long_df[["Month"]]
y = long_df["Temperature"]

long_df.head()

""">

2. Assess the performance of regression models using MSE, MAE and R-Square
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Size:", X_train.shape)
print("Testing Size:", X_test.shape)

print("Mean Squared Error (MSE):", mse)

print("Mean Absolute Error (MAE):", mae)

print("R-Square (R2 Score):", r2)

""">

3. Metrics
"""

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("R-Square (R2 Score):", r2)

""">

>

4. Visualize a simple regression model.
"""

# Scatter plot
plt.figure()
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("Month (1-12)")
plt.ylabel("Temperature (°C)")
plt.title("Linear Regression: Month vs Temperature")

plt.show()