# -*- coding: utf-8 -*-
"""ML-6_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek_JBlqJv0JLu3GAFa2DgVT6vWhX_rO7

# **Machine Learning Assignment :- 6**

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

**   **
Use the diabetes data set from UCI and Pima Indians Diabetes data set for performing the following:

a. Univariate analysis: Frequency, Mean, Median, Mode, Variance, Standard Deviation, Skewness and Kurtosis

b. Bivariate analysis: Linear and logistic regression modeling

c. Multiple Regression analysis

d. Also compare the results of the above analysis for the two data sets.

DATASET LINK :- [ https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database]( https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import skew, kurtosis
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, confusion_matrix
import statsmodels.api as sm

data = pd.read_csv("diabetes.csv")
print("Original Shape:", data.shape)
data.head()

zero_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in zero_columns:
    data[col] = data[col].replace(0, np.nan)

clean_data = data.dropna()

print("Cleaned Shape:", clean_data.shape)

"""#

** **


#


#A. Univariate Analysis: Frequency, Mean, Median, Mode, Variance, Standard Deviation, Skewness and Kurtosis
"""

print("Outcome Distribution:")
print(clean_data["Outcome"].value_counts())

uni_stats = pd.DataFrame()

uni_stats["Mean"] = clean_data.mean()
uni_stats["Median"] = clean_data.median()
uni_stats["Mode"] = clean_data.mode().iloc[0]
uni_stats["Variance"] = clean_data.var()
uni_stats["Std_Deviation"] = clean_data.std()
uni_stats["Skewness"] = clean_data.apply(skew)
uni_stats["Kurtosis"] = clean_data.apply(kurtosis)

print("Univariate Analysis Summary")
display(uni_stats)

plt.figure(figsize=(10,5))
plt.bar(uni_stats.index, uni_stats["Skewness"])
plt.xticks(rotation=45)
plt.axhline(0, linestyle="--")
plt.title("Feature Skewness")
plt.show()

"""** **
# B. Bivariate Analysis: Linear and logistic regression modeling
"""

correlation_matrix = clean_data.corr()

print("Correlation Matrix:")
print(correlation_matrix)

X_lr = clean_data[["Glucose"]]
y_lr = clean_data["Insulin"]

X_train, X_test, y_train, y_test = train_test_split(
    X_lr, y_lr, test_size=0.3, random_state=1
)

linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

predictions = linear_model.predict(X_test)

print("Linear Regression Output")
print("Slope:", linear_model.coef_[0])
print("Intercept:", linear_model.intercept_)
print("R2 Score:", r2_score(y_test, predictions))
print("MSE:", mean_squared_error(y_test, predictions))

plt.scatter(X_test, y_test)
plt.plot(X_test, predictions)
plt.xlabel("Glucose")
plt.ylabel("Insulin")
plt.title("Linear Regression Fit")
plt.show()

X_log = clean_data.drop("Outcome", axis=1)
y_log = clean_data["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X_log, y_log, test_size=0.3, random_state=1
)

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

log_predictions = log_model.predict(X_test)

print("Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, log_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, log_predictions))

"""** **








#

#

#



#  C. Multiple Regression Analysis


"""

X_multi = clean_data.drop("Outcome", axis=1)
y_multi = clean_data["Outcome"]

X_multi = sm.add_constant(X_multi)

multi_reg_model = sm.OLS(y_multi, X_multi).fit()

print(multi_reg_model.summary())

"""** **
#D. Also compare the results of the above analysis for the two data sets.
"""

uci_data = pd.read_csv("diabetes.csv")

print("UCI Dataset Shape:", uci_data.shape)
print("Pima Dataset Shape (Cleaned):", clean_data.shape)

if len(uci_data.columns) == len(clean_data.columns):
    print("both datasets have same features.")
else:
    print("Feature mismatch found.")

print("UCI Outcome Distribution:")
print(uci_clean_data["Outcome"].value_counts())

uci_uni_stats = pd.DataFrame()
uci_uni_stats["Mean"] = uci_clean_data.mean()
uci_uni_stats["Median"] = uci_clean_data.median()
uci_uni_stats["Mode"] = uci_clean_data.mode().iloc[0]
uci_uni_stats["Variance"] = uci_clean_data.var()
uci_uni_stats["Std_Deviation"] = uci_clean_data.std()
uci_uni_stats["Skewness"] = uci_clean_data.apply(skew)
uci_uni_stats["Kurtosis"] = uci_clean_data.apply(kurtosis)
print("\nUCI Univariate Analysis Summary")
display(uci_uni_stats)

uci_correlation_matrix = uci_clean_data.corr()

print("UCI Correlation Matrix:")
print(uci_correlation_matrix)