# -*- coding: utf-8 -*-
"""ML@ Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9OfXBsaqb0svDJILeyfCds-PdQkEiR9

# **Machine Learning Assignment :- 2**

Name: Ghrushnesh Sudhakar Patil

Class: CSAI-D     

Batch : 3

Roll No: 66

PRN: 12411658

Perform the following operations using  Python on the data sets:

Compute and display summary statistics for each feature available in the dataset. (e.g. minimum value, maximum value, mean, range, standard deviation, variance and percentiles
Illustrate the feature distributions using histogram.
Data cleaning, Data integration, Data transformation, Data model building (e.g. Classification))
"""

import pandas as pd
import numpy as np

"""Load the Dataset"""

df = pd.read_csv('data.csv')

df.head

"""Dataset Shape & Structure

"""

df.shape

df.info

df.dtypes

"""Data Cleaning"""

df.isnull().sum()

"""Handle missing values

Summary Statistics
"""

df.describe

"""Detailed statistics

Mean
"""

summary = pd.DataFrame({
    "Minimum": df.min(numeric_only=True),
    "Maximum": df.max(numeric_only=True),
    "Mean": df.mean(numeric_only=True),
    "Range": df.max(numeric_only=True) - df.min(numeric_only=True),
    "Variance": df.var(numeric_only=True),
    "Standard Deviation": df.std(numeric_only=True),
    "25%": df.quantile(0.25, numeric_only=True),
    "50% (Median)": df.quantile(0.50, numeric_only=True),
    "75%": df.quantile(0.75, numeric_only=True)
})


summary

df["energy"].min()

df["tempo"].max()

df["duration_ms"].var()

df["liveness"].std()

"""User Defined Functions"""

import pandas as pd
import numpy as np

df = pd.read_excel("employee_data_45_rows.xlsx")
print(df.columns)

column_data = df["Age"].tolist()

"""Mean"""

def mean(col):
     return sum(col) / len(col)

print("Mean =", mean(column_data))

"""median"""

def median(col):
    s = sorted(col)
    n = len(s)
    if n % 2 == 0:
        return (s[n//2 - 1] + s[n//2]) / 2
    else:
        return s[n//2]

print("Median =", median(column_data))

"""Mode"""

def mode(col):
    freq = {}
    for i in col:
        freq[i] = freq.get(i, 0) + 1
    max_freq = max(freq.values())
    return [k for k, v in freq.items() if v == max_freq]

print("Mode =", mode(column_data))

"""Variance"""

def variance(col):
    m = mean(col)
    total = 0
    for i in col:
        total += (i - m) ** 2
    return total / len(col)

print("Variance =", variance(column_data))

"""Standard Deviation"""

import math

def std_dev(col):
    return math.sqrt(variance(col))

print("Standard Deviation =", std_dev(column_data))

"""Min"""

def minimum(col):
    min_val = col[0]
    for x in col:
        if x < min_val:
            min_val = x
    return min_val

print("Minimum =", minimum(column_data))

"""Max"""

def maximum(col):
    max_val = col[0]
    for x in col:
        if x > max_val:
            max_val = x
    return max_val

print("Maximum =", maximum(column_data))

"""Range"""

def data_range(col):
    return maximum(col) - minimum(col)

print("Range =", data_range(column_data))

"""Histogram"""

import matplotlib.pyplot as plt

plt.hist(column_data, bins=10)
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.title("Histogram of Age ")
plt.show()

"""Data cleaning

Handling missing values
"""

df.isnull()

df.notnull()

"""a. drop rows containing atleast one NaN"""

df_drop_rows = df.dropna()
print(df_drop_rows)

"""b Drop columns containing NaN"""

df_drop_cols = df.dropna(axis=1)
print(df_drop_cols)

"""a Fill all NaN values with 0"""

df_fill_zero = df.fillna(0)
print(df_fill_zero)

"""b Fill NaN with column mean"""

df_fill_mean = df.fillna(df.mean(numeric_only=True))
print(df_fill_mean)

df_interpolated = df.interpolate()
print(df_interpolated)

df_replace = df.replace(np.nan, "Not Available")
print(df_replace)

"""Removing Duplicates"""

df.duplicated()

"""for specific column"""

df.duplicated(subset=["ID"])

"""drop duplicates"""

df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)

"""Remove Duplicates Based on One Column"""

df_unique_id = df.drop_duplicates(subset=["ID"])
print(df_unique_id)

"""Keep Last Duplicate Instead of First"""

df_keep_last = df.drop_duplicates(keep="last")
print(df_keep_last)

"""Remove All Duplicates"""

df_remove_all = df.drop_duplicates(keep=False)
print(df_remove_all)

"""Data Type conversion

1. astype()
"""

df["Age"] = df["Age"].astype(int)
print(df.dtypes)

df["Rating"]=df["Rating"].astype(int)
print(df.dtypes)

"""2. to_numeric()"""

df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
print(df["Salary"])

"""3. convert_dtypes()"""

df_converted = df.convert_dtypes()

print(df.dtypes)
print(df_converted.dtypes)

"""Remaining column and index

1. Rename
"""

df_rename = df.rename(columns={"Age": "Employee_Age"})
print(df_rename.columns)

df_rename_index = df.rename(index={0: "Row_1", 1: "Row_2"})
print(df_rename_index.head())

"""2. rename_axis()"""

df_axis_index = df.rename_axis("Employee_ID", axis="index")
print(df_axis_index.head())

df_axis_column = df.rename_axis("Employee_Details", axis="columns")
print(df_axis_column)

"""3. set_axis()"""

df_set_index = df.set_axis(range(1, len(df) + 1), axis=0)
print(df_set_index.head())

"""4. add_prefix()"""

df_prefix = df.add_prefix("emp_")
print(df_prefix.columns)

"""5. add_suffix"""

df_suffix = df.add_suffix("_info")
print(df_suffix.columns)

"""Handling incorrect or inconsistant data

1. replace()
"""

df["Salary"] = df["Salary"].replace(-1, 0)
df["Salary"] = df["Salary"].where(df["Salary"] >= 30000)

"""2. map()"""

def bonus(salary):
    return salary + 2000

df["Salary"] = df["Salary"].apply(bonus)
print(df["Salary"])

def category(row):
    if row["Salary"] > 50000:
        return "High"
    else:
        return "Normal"

df["Category"] = df.apply(category, axis=1)
print(df["Category"])

"""3. applymap()"""

df_lower = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
print(df_lower)

"""4. where()"""

df["Salary"] = df["Salary"].where(df["Salary"] >= 30000)
print(df["Salary"])

"""5. mask()"""

df["Salary"] = df["Salary"].mask(df["Salary"] < 30000)
print(df["Salary"])

"""String Cleaning

1. Create a Text Column
"""

df["Dept_Name"] = " dept_" + df["Dept_ID"].astype(str) + " "
print(df["Dept_Name"].head())

"""str.lower()"""

df["Dept_Name"] = df["Dept_Name"].str.lower()
print(df["Dept_Name"].head())

"""str.upper()"""

df["Dept_Name"] = df["Dept_Name"].str.upper()
print(df["Dept_Name"].head())

"""str.title()"""

df["Dept_Name"] = df["Dept_Name"].str.title()
print(df["Dept_Name"].head())

"""str.strip()"""

df["Dept_Name"] = df["Dept_Name"].str.strip()
print(df["Dept_Name"].head())

"""str.lstrip()"""

df["Dept_Name"] = df["Dept_Name"].str.lstrip()

"""str.rstrip()"""

df["Dept_Name"] = df["Dept_Name"].str.rstrip()

"""str.replace()"""

df["Dept_Name"] = df["Dept_Name"].str.replace("Dept_", "Department_", regex=False)
print(df["Dept_Name"].head())

"""str.contains()"""

df["Is_Department_1"] = df["Dept_Name"].str.contains("1")
print(df[["Dept_Name", "Is_Department_1"]].head())

"""str.split()"""

df["Dept_Split"] = df["Dept_Name"].str.split("_")
print(df["Dept_Split"].head())

"""str.extract()"""

df["Dept_Number"] = df["Dept_Name"].str.extract(r"(\d+)")
print(df[["Dept_Name", "Dept_Number"]].head())

"""str.len()"""

df["Dept_Length"] = df["Dept_Name"].str.len()
print(df[["Dept_Name", "Dept_Length"]].head())

"""Handling Outliers

1. describe
"""

df.describe()

"""2. quantile"""

df["Salary"].quantile(0.25)   # Q1

df["Salary"].quantile(0.50)   # Median

df["Salary"].quantile(0.75)   # Q3

Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1

"""3. clip()"""

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df["Salary_Clipped"] = df["Salary"].clip(lower, upper)
print(df[["Salary", "Salary_Clipped"]].head())

"""4. between()"""

df["Salary_Valid"] = df["Salary"].between(lower, upper)
print(df[["Salary", "Salary_Valid"]].head())

df_no_outliers = df[df["Salary"].between(lower, upper)]
print(df_no_outliers["Salary"].head())

"""Index and Row operations

1. reset_index()
"""

df_reset = df.reset_index()
print(df_reset.head())

df_reset_drop = df.reset_index(drop=True)
print(df_reset_drop.head())

"""2. set_index()"""

df_id_index = df.set_index("ID")
print(df_id_index.head())

"""3. reindex()"""

new_index = [1, 3, 5, 7, 9]
df_reindexed = df_id_index.reindex(new_index)
print(df_reindexed)

"""4. sort_index()"""

df_sorted_index = df_id_index.sort_index()
print(df_sorted_index.head())

df_sorted_desc = df_id_index.sort_index(ascending=False)
print(df_sorted_desc.head())

"""Sorting and filtering

1. sort_values()
"""

df_sorted_salary = df.sort_values(by="Salary")
print(df_sorted_salary.head())

df_sorted_salary_desc = df.sort_values(by="Salary", ascending=False)
print(df_sorted_salary_desc.head())

df_sorted_multi = df.sort_values(by=["Dept_ID", "Salary"])
print(df_sorted_multi.head())

"""2. query()"""

df_high_salary = df.query("Salary > 50000")
print(df_high_salary)

"""3. filter()"""

df.filter(["Age", "Salary", "Experience"])

df.filter(like="ID")

df.filter(items=[1, 3, 5], axis=0)

"""Data Validation & Inspection

1. info()
"""

df.info()

"""2. head()"""

df.head()

df.head(10)

"""3. tail()"""

df.tail()

"""4. sample()"""

df. sample(5)

"""5. shape"""

df.shape

"""6. column"""

df.columns

"""7. dtypes"""

df.dtypes

"""8. value_counts()"""

df["Gender_ID"].value_counts()

df["Target_Churn"].value_counts(normalize=True)

"""Handling Categorical Data

1. astype('category')
"""

df["Dept_ID"] = df["Dept_ID"].astype("category")
print(df.dtypes)

"""2. cat.categories"""

df["Dept_ID"].cat.categories

"""3 cat.rename_categories()"""

df["Dept_ID"] = df["Dept_ID"].cat.rename_categories({
    1: "HR",
    2: "IT",
    3: "Finance",
    4: "Sales"
})
df["Dept_ID"].cat.categories

"""4. cat.codes"""

df["Dept_Code"] = df["Dept_ID"].cat.codes
print(df[["Dept_ID", "Dept_Code"]].head())

"""5. get_dummies()"""

gender_dummies = pd.get_dummies(df["Gender_ID"], prefix="Gender")
print(gender_dummies.head())

"""Handling Date & Time Data"""

import pandas as pd

date_df = pd.DataFrame({
    "Employee_ID": [1, 2, 3, 4, 5],
    "Login_Time": pd.to_datetime([
        "2024-01-10 09:15:00",
        "2024-02-12 10:30:00",
        "2024-03-15 08:45:00",
        "2024-04-18 11:00:00",
        "2024-05-20 09:00:00"
    ])
})

print(date_df)

"""1. dt.year"""

date_df["Year"] = date_df["Login_Time"].dt.year
print(date_df)

"""2. dt.month"""

date_df["Month"] = date_df["Login_Time"].dt.month
print(date_df)

"""3. dt.day"""

date_df["Day"] = date_df["Login_Time"].dt.day
print(date_df)

"""4. dt.hour"""

date_df["Hour"] = date_df["Login_Time"].dt.hour
print(date_df)

"""5. dt.strftime()"""

date_df["Formatted_Date"] = date_df["Login_Time"].dt.strftime("%d-%m-%Y %H:%M")
print(date_df)

"""6. dt.tz_localize()"""

date_df["Login_Time_IST"] = date_df["Login_Time"].dt.tz_localize("Asia/Kolkata")
print(date_df)

"""7. dt.tz_convert()"""

date_df["Login_Time_UTC"] = date_df["Login_Time_IST"].dt.tz_convert("UTC")
print(date_df)

"""Removing / Selecting Columns

1. drop()
"""

df_drop_col = df.drop(columns=["Bonus"])
print(df_drop_col.columns)

"""2. pop()"""

salary_col = df.pop("Salary")
print(salary_col.head())

"""3. filter()"""

df_selected = df.filter(["Age", "Experience", "Salary"])
print(df_selected.head())

df_id_cols = df.filter(like="ID")
print(df_id_cols.head())

df_rows = df.filter(items=[1, 3, 5], axis=0)
print(df_rows)

"""Combining & Reshaping Data

1. Merge
"""

dept_df = pd.DataFrame({
    "Dept_ID": [1, 2, 3, 4],
    "Dept_Name": ["HR", "IT", "Finance", "Sales"]
})

merged_df = pd.merge(df, dept_df, on="Dept_ID", how="inner")
print(merged_df.head())

"""2. join

Setting index
"""

df_indexed = df.set_index("Dept_ID")
dept_indexed = dept_df.set_index("Dept_ID")

joined_df = df_indexed.join(dept_indexed)
print(joined_df.head())

"""3. concat

row wise
"""

df_part1 = df.iloc[:10]
df_part2 = df.iloc[10:20]

concat_rows = pd.concat([df_part1, df_part2])
print(concat_rows.shape)

"""column wise"""

extra_df = df[["ID", "Salary"]]

concat_cols = pd.concat([df, extra_df], axis=1)
print(concat_cols.head())

"""4. pivot"""

pivot_table_df = pd.pivot_table(
    df,
    values="Salary",
    index="Dept_ID",
    aggfunc="mean"
)
print(pivot_table_df)

pivot_table_multi = pd.pivot_table(
    df,
    values="Salary",
    index="Dept_ID",
    aggfunc=["mean", "max", "min"]
)
print(pivot_table_multi)

"""6. melt"""

melt_df = pd.melt(
    df,
    id_vars=["ID"],
    value_vars=["Salary", "Bonus"],
    var_name="Income_Type",
    value_name="Amount"
)

print(melt_df.head())

"""Reading dirty data"""

df_excel = pd.read_excel("employee_data_45_rows.xlsx", sheet_name="Sheet1")
print(df_excel.head())

"""Data Integration"""

import pandas as pd

df = pd.read_excel("employee_data_45_rows.xlsx")

extra_data = pd.DataFrame({
    "ID": df["ID"].head(45),          # matching key
    "Employment_Type": ["Private"] * 45
})

print(extra_data.head())

df = pd.merge(df, extra_data, on="ID", how="left")

print(df.head())
print(df.columns)

"""ex. 2"""

dept_category = pd.DataFrame({
    "Dept_ID": [1, 2, 3, 4],
    "Dept_Category": ["Admin", "Technical", "Finance", "Sales"]
})

df = pd.merge(df, dept_category, on="Dept_ID", how="left")
print(df.columns)

"""Data Transformation"""

import pandas as pd

df = pd.read_excel("employee_data_45_rows.xlsx")

"""Label Encoding"""

from sklearn.preprocessing import LabelEncoder

categorical_cols = ["Dept_ID", "Gender_ID"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

print("Label Encoding Completed")

"""Feature scaling"""

from sklearn.preprocessing import StandardScaler

numeric_cols = [
    "Age", "Experience", "Salary", "Projects", "Hours_Worked",
    "Distance_KM", "Training_Days", "Rating", "Bonus",
    "Sick_Leaves", "Satisfaction"
]

scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("Feature Scaling Completed")

print(df.head())
print(df.dtypes)