# -*- coding: utf-8 -*-
"""ML --ASSIGNMENT --13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRlUQB5tBBysHwK_HPNRAWOxsP8lycev

# **Machine Learning Assignment :- 13**

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

---






**Q. Implement K-Means clustering on Iris.csv dataset. Determine the number of clusters using the elbow method.**

 **DATASET LINK :- https://www.kaggle.com/datasets/uciml/iris**


---
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

"""#Dataset"""

iris = load_iris()
dataset = pd.DataFrame(data=iris.data, columns=iris.feature_names)
dataset.head()
dataset.info()
dataset.describe()
dataset.isnull().sum()

"""#Data Scatter Plot"""

plt.scatter(dataset.iloc[:, 0], dataset.iloc[:, 1])
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Iris Data Distribution")
plt.show()

"""#Elbow Method

"""

X = dataset.values
wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=17)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()

"""#Silhouette Score"""

sil_scores = []
for i in range(2,11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
  labels = kmeans.fit_predict(X)
  score = silhouette_score(X, labels)
  sil_scores.append(score)
  print(f"K = {i}, Silhouette Score = {score:.4f}")

plt.plot(range(2,11), sil_scores, marker='o')
plt.title("Silhouette Score")
plt.xlabel("Number of Clusters")
plt.ylabel("Score")
plt.show()

"""#Clustering"""

kmeans = KMeans(n_clusters=3, init='k-means++', random_state=12)
y_kmeans = kmeans.fit_predict(X)

plt.figure(figsize=(8,6))
plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1], s=100, c='red', label='Cluster 1')
plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1], s=100, c='blue', label='Cluster 2')
plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1], s=100, c='green', label='Cluster 3')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1],
s=300, c='yellow', label='Centroids')
plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Iris Clusters")
plt.legend()
plt.show()