# -*- coding: utf-8 -*-
"""ML Assignment-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5_Nd00WDeXCM1E26wRiah13ynujL-Ag

# **Machine Learning Assignment :- 3**

**   **
**Name: Ghrushnesh Sudhakar Patil**

**Class: CSAI-D**     

**Batch : 3**

**Roll No: 66**

**PRN: 12411658**

Visualize the data using Python by plotting the graphs for assignment no. 1 and 2. Consider a suitable data set. Use Scatter plot, Bar plot, Box plot, Pie chart, Line Chart.
"""



import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

names = [
    "Ghrushnesh", "Riya", "Rahul", "Neha", "Arjun",
    "Priya", "Karan", "Sneha", "Harish", "Anjali",
    "Rohit", "Pooja", "Sagar", "Kavya", "Suresh"
]

gender = [
    "Male", "Female", "Male", "Female", "Male",
    "Female", "Male", "Female", "Male", "Female",
    "Male", "Female", "Male", "Female", "Male"
]

cities = [
    "Pune", "Mumbai", "Delhi", "Pune", "Bangalore",
    "Mumbai", "Delhi", "Pune", "Bangalore", "Mumbai",
    "Delhi", "Pune", "Bangalore", "Mumbai", "Delhi"
]

marks = [89, 77, 49, 90, 34, 88, 92, 81, 19, 95, 27, 86, 46, 62, 95]
grade = ["Pass", "Pass", "Fail", "Pass", "Fail", "Pass",
         "Pass", "Pass", "Fail", "Pass", "Fail", "Pass",
         "Fail", "Pass", "Pass"]
attendance = [82, 90, 75, 95, 80, 92, 96, 88, 70, 98, 78, 91, 85, 89, 94]

"""# Bar Chart"""

plt.figure(figsize=(10,5))
plt.bar(names, marks)
plt.xlabel("Student Name")
plt.ylabel("Marks")
plt.title("Bar Chart: Marks vs Name")
plt.xticks(rotation=45)
plt.show()

"""# Scatter Plot"""

city_map = {
    "Pune": 1,
    "Mumbai": 2,
    "Delhi": 3,
    "Bangalore": 4
}

city_values = [city_map[city] for city in cities]
student_index = list(range(1, len(names) + 1))

male_x = [student_index[i] for i in range(len(gender)) if gender[i] == "Male"]
male_y = [city_values[i] for i in range(len(gender)) if gender[i] == "Male"]

female_x = [student_index[i] for i in range(len(gender)) if gender[i] == "Female"]
female_y = [city_values[i] for i in range(len(gender)) if gender[i] == "Female"]

plt.figure(figsize=(10,5))
plt.scatter(male_x, male_y, marker='o', label='Male')
plt.scatter(female_x, female_y, marker='^', label='Female')

plt.xticks(student_index, names, rotation=45)
plt.yticks(
    [1, 2, 3, 4],
    ["Pune", "Mumbai", "Delhi", "Bangalore"]
)

plt.xlabel("Students")
plt.ylabel("Cities")
plt.title("Scatter Plot: Students vs Cities by Gender")
plt.legend()
plt.show()

"""# Pie Chart"""

city_counts = {
    "Pune": cities.count("Pune"),
    "Mumbai": cities.count("Mumbai"),
    "Delhi": cities.count("Delhi"),
    "Bangalore": cities.count("Bangalore")
}

plt.figure()
plt.pie(
    city_counts.values(),
    labels=city_counts.keys(),
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Pie Chart: City-wise Student Distribution")
plt.legend()
plt.show()

"""# Box Plot"""

plt.figure()
plt.boxplot(marks)
plt.ylabel("Marks")
plt.title("Box Plot: Marks Distribution")
plt.show()

"""# Line Chart"""

city_data = {
    "Pune": ([], []),
    "Mumbai": ([], []),
    "Delhi": ([], []),
    "Bangalore": ([], [])
}

for i in range(len(names)):
    city_data[cities[i]][0].append(names[i])
    city_data[cities[i]][1].append(attendance[i])

plt.figure(figsize=(15,10))
plt.plot(city_data["Pune"][0], city_data["Pune"][1], label="Pune", color="blue", marker='o')
plt.plot(city_data["Mumbai"][0], city_data["Mumbai"][1], label="Mumbai", color="green", marker='o')
plt.plot(city_data["Delhi"][0], city_data["Delhi"][1], label="Delhi", color="red", marker='o')
plt.plot(city_data["Bangalore"][0], city_data["Bangalore"][1], label="Bangalore", color="purple", marker='o')

plt.xlabel("Student Name")
plt.ylabel("Attendance (%)")
plt.title("Line Chart: Attendance Trend by City")
plt.xticks(rotation=45)
plt.legend()
plt.show()

"""# Heat Map"""

data = np.array([marks, attendance])

plt.figure(figsize=(10,4))
heatmap = plt.imshow(data)

plt.xticks(range(len(names)), names, rotation=45)
plt.yticks([0, 1], ["Marks", "Attendance"])

cbar = plt.colorbar(heatmap)
cbar.set_label("Value Scale (Low → High)")

plt.title("Heat Map: Marks and Attendance of Students")
plt.show()