# -*- coding: utf-8 -*-
"""ML-ASG-11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16njSD3dzLVXKiCBVA4zuZDtkYdY3AIrj

Assignment 11

Name: Panchal Sagar Nandkumar

Class: CSAI-D   

Batch : 3

Roll No: 50

PRN: 12411293

Q. 11. Assignment on Classification technique. Every year many students give the GRE exam to get admission in foreign Universities. The data set contains GRE Scores (out of 340), TOEFL Scores (out of 120), University Rating (out of 5), Statement of Purpose strength (out of 5), Letter of Recommendation strength (out of 5), Undergraduate GPA (out of 10), Research Experience (0=no, 1=yes), Admitted (0=no, 1=yes). Admitted is the target variable.

DATASET LINK :- [https://www.kaggle.com/mohansacharya/graduate-admissions](https://www.kaggle.com/mohansacharya/graduate-admissions)


The counsellor of the firm is supposed check whether the student will get an admission or not based on his/her GRE score and Academic Score. So to help the counsellor to make appropriate decisions, build a machine learning model classifier using a Decision tree to predict whether a student will get admission or not.  Apply Data pre-processing (Label Encoding, Data Transformation….) techniques if necessary.



1.   Perform data-preparation (Train-Test Split)

2.   Apply Machine Learning Algorithm

3.   Evaluate Model.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Loaded dataset
df = pd.read_csv("Admission_Predict_Ver1.1.csv")
df.shape

# Removeing extra spaces from column names
df.columns = df.columns.str.strip()
df.columns

# Display first 5 rows
print("First 5 rows of dataset:")
print(df.head())

""">

>
"""

# Checked missing values
print("\nMissing values:")
print(df.isnull().sum())

# Create binary target variable from Chance of Admit
df['Admitted'] = (df['Chance of Admit'] >= 0.75).astype(int)

X = df[['GRE Score', 'CGPA']]
y = df['Admitted']

print(X.head())
print(y.head)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Build Decision Tree model
model = DecisionTreeClassifier(random_state=42, max_depth=3)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

""">

>

>
"""

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))